# fly.toml app configuration file generated for binance-tracker-summer-mountain-2061 on 2025-09-20T15:28:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'binance-tracker-summer-mountain-2061'
primary_region = 'jnb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
