app = "backend-nameless-tree-1515"

[build]
  # Use the default Node.js build
  image = "node:18"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["http"]
